config/routes.rb
Rails.application.routes.draw do

  root to: "searches#index"

  resources :searches
  resources :users
  resources :saved_streets
  resource :session, only: [ :new, :create, :destroy ]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Boston Street Sweeping Notifications", root_path, class:"navbar-brand" %>
    </div>
    <div class="navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <p class="navbar-text">or</p>
        </li>
          <%= link_to new_user_path do %>
            <button type="button" class="btn btn-success navbar-btn">Sign Up For Notifications</button>
          <% end %>
      </ul>
      <form action="/session" accept-charset="UTF-8" method="post" class="navbar-form navbar-right">
        <div class="form-group">
          <input name="utf8" type="hidden" value="✓">
          <input type="hidden" name="authenticity_token"
      value="<%= form_authenticity_token %>">
          <input type="text" name="email" id="email" class="form-control" placeholder="Email">
         
          <input type="password" name="password" id="password" class="form-control" placeholder="Password">
         
          <input type="submit" name="commit" value="Log In!" class="btn btn-primary">
        </div>
      </form>

    </div>

  </div>
</nav>

app/views/shared/_signed_in_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Boston Street Sweeping Notifications", root_path, class:"navbar-brand" %>
    </div>
    <div class="navbar-collapse">

      <ul class="nav navbar-nav navbar-right">
        <li><p class="navbar-text">Signed in as <%= link_to current_user.email, user_path(current_user) %></li>
        <li><%= link_to "Logout", session_path, :method => :delete %></li>
      </ul>
    </div>

  </div>
</nav>