config/routes.rb
Rails.application.routes.draw do

  root to: "searches#index"

  resources :searches
  resources :users
  resources :saved_streets
  resource :session, only: [ :new, :create, :destroy ]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController  

  def index
    @streets = street_names
    @street = params[:street] || nil
    if @street
      if street_names.include?(@street)
        @results = client.get("wisd-cxpy", {:street => "#{@street}"})
      else
        flash[:danger] = "Please choose a street that exists and stop messing with inspect tools"
      end
    end
        
  end


end

app/helpers/searches_helper.rb
module SearchesHelper



  def schedule(result)
    output = "Every "
    unless result["week1"] == "True" && result["week2"] == "True" && result["week3"] == "True" && result["week4"] == "True" && result["week5"] == "True"
      if result["week1"] == "True"
        output += "first, "
      elsif result["week2"] == "True"
        output += "second, "
      elsif result["week3"] == "True"
        output += "third, " 
      elsif result["week4"] == "True"
        output += "fourth, "
      elsif result["week5"] == "True"
        output += "fifth, "
      end
      output[-2..-1] = " "
    end
    if result["monday"] == "True" && result["tuesday"] == "True" && result["wednesday"] == "True" && result["thursday"] == "True" && result["friday"] == "True" && result["saturday"] == "True" && result["sunday"] == "True"
      output += "day from "
    else
      if result["monday"] == "True"
        output += "Monday, "
      elsif result["tuesday"] == "True"
        output += "Tuesday, "
      elsif result["wednesday"] == "True"
        output += "Wednesday, " 
      elsif result["thursday"] == "True"
        output += "Thursday, " 
      elsif result["friday"] == "True"
        output += "Friday, " 
      elsif result["saturday"] == "True"
        output += "Saturday, " 
      elsif result["sunday"] == "True"
        output += "Sunday, "
      end
      output[-2..-1] = " from "
    end
    output += result["starttime"].to_time.strftime("%l %p") 
    output += " to "
    output += result["endtime"].to_time.strftime("%l %p")
    output
  end
  
end

app/views/searches/_notify.html.erb
<% if signed_in_user? %>
  <% if current_user.saved_streets.any?{|s| s.street_id == street_id} %>
    <%= link_to "Remove from Saved Streets", saved_street_path(current_user.saved_street(street_id)), method: "delete", class:"btn btn-danger" %>
  <% else %>
    <%= link_to "Save To Your Streets", saved_streets_path(street_id: street_id), method: "post", class:"btn btn-primary" %>
  <% end %>
  
<% else %>
  <%= link_to "Sign Up For Notifications", new_user_path, class:"btn btn-primary" %> or <%= link_to "sign in", new_session_path %>
<% end %>

app/views/searches/_street_info.html.erb
<tr>
  <td><%= result["street"] %></td>
  <td><%= result["side"] %></td>
  <td>From <%= result["from"] %> to <%= result["to"] %></td>
  <td><%= schedule(result) %></td>
  <td><%= render partial: "searches/notify", locals: {street_id: result["crossstreetmainid"]} %></td>
</tr>

app/views/searches/index.html.erb
<h3> Welcome to Boston Street Sweeping Notifications. Use this tool to never get towed again. Just choose your street below to see what days of the week different stretches of the street can cleaned.</h3>

<h3>Choose Your Street</h3>

<%= form_tag searches_path, :method => 'get' do %>
  <%= select_tag :street, options_for_select(@streets) %>
  <%= submit_tag "Search", class:"btn btn-primary" %>
<% end %>

<% if @results %>
  <h1>Street Sweeping Info for <%= "#{@street}" %></h1>
  <div class="table-responsive">
    <table class="table table-striped table-hover table-condensed">
      <tr>
        <th>Street</th>
        <th>Side</th>
        <th>Between</th>
        <th>Schedule</th>
        <th>Notify Me!</th>
      </tr>
      <% @results.each do |result| %>
        <%= render partial: "street_info", locals: {result: result} %>
      <% end %>
    </table>
  </div>
  <% if signed_in_user? %>
    <h3>By clicking "Save To Your Sheets", you will receive an email notification at the email address associated with your account the night before street sweeping.</h3>
    <h4><%= link_to "View Your Account", user_path(current_user) %></h4>
  <% else %>
    <h4>Don't have an account? <%= link_to "Click here", new_user_path %> to sign up.</h4>
  <% end %>
<% end %>